# Generated by Django 4.0.5 on 2022-07-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_home_page_investor_home_page_slide_plans_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_page',
            name='site_top_investor',
        ),
        migrations.DeleteModel(
            name='home_page_slide',
        ),
        migrations.DeleteModel(
            name='plans',
        ),
        migrations.DeleteModel(
            name='home_page',
        ),
        migrations.DeleteModel(
            name='home_page_investor',
        ),
    ]
