# Generated by Django 4.0.5 on 2022-07-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_kyc_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='non_withdrawal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='withdrawal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
