# Generated by Django 4.0.5 on 2022-07-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userdetail_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='non_withdrawal',
            field=models.IntegerField(blank=True, default='000', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='withdrawal',
            field=models.IntegerField(blank=True, default='000', null=True),
        ),
    ]
