# Generated by Django 4.0.5 on 2022-07-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_page_investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('person_pic', models.ImageField(upload_to='')),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_join', models.DateField(blank=True, null=True)),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='home_page_slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_max_pay', models.CharField(max_length=50)),
                ('plan_duration', models.CharField(max_length=50)),
                ('plan_min_pay', models.CharField(max_length=50)),
                ('plan_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='home_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=50, null=True)),
                ('site_contact_number', models.URLField(blank=True, null=True)),
                ('site_disc', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('tweeter_link', models.URLField(blank=True, null=True)),
                ('instargram_link', models.URLField(blank=True, null=True)),
                ('site_top_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.home_page_investor')),
            ],
        ),
    ]
