# Generated by Django 4.0.5 on 2022-07-04 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='home_page',
            name='site_top_investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homePage.home_page_investor'),
        ),
        migrations.AlterField(
            model_name='home_page_investor',
            name='person_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='home_page_slide',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
