# Generated by Django 4.0.5 on 2022-07-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_alter_home_page_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='site_contact_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
