# Generated by Django 4.0.5 on 2022-07-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_alter_home_page_site_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
